---
- name: Determine Tasks for Workstation
  ansible.builtin.include_tasks:
    file: "{{ tasks }}"
  loop:
    - "./os/Ubuntu.yml"
  loop_control:
    loop_var: tasks
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Determine Tasks for Workstation
  ansible.builtin.include_tasks:
    file: "{{ tasks }}"
  loop:
    - "./os/Fedora.yml"
  loop_control:
    loop_var: tasks
  when: ansible_facts['distribution'] == "Fedora"

- name: Install VS Code Extensions
  become: false
  ansible.builtin.command:
    cmd: 'code --install-extension {{ item }}'
    creates: '~/.vscode/extensions/{{ item }}*'
  loop:
    - ms-vscode.cpptools-extension-pack
    - ms-dotnettools.csharp
    - ms-python.python
    - ms-python.vscode-pylance
    - pkief.material-icon-theme
    - redhat.vscode-yaml
    - vscodevim.vim
    - zhuangtongfa.material-theme
    - hashicorp.terraform

- name: Copy Configs
  become: false
  ansible.builtin.copy:
    src: configs/
    dest: ~/
    mode: 0664

- name: Clone oh-my-zsh
  become: false
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/.oh-my-zsh
    version: master
