---
- name: Add GPG Keys for Fedora
  become: true
  ansible.builtin.rpm_key:
    key: "{{ item }}"
    state: present
  loop:
    - 'https://packages.microsoft.com/keys/microsoft.asc'

- name: Add Repositories
  become: true
  ansible.builtin.copy:
    src: 'repos/'
    dest: '/etc/yum.repos.d/'
    mode: 0664

- name: Install Tools
  become: true
  ansible.builtin.package:
    name:
      - git
      - bat
      - tmux
      - vim
      - zsh
      - code
      - powerline-fonts
      - podman
      - virt-manager
    state: 'present'

- name: Modify User Account
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups:
      - wheel
      - libvirt
    append: true
    shell: /bin/zsh
